version: '3.8'
services:
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos

  kratos-migrate:
    depends_on:
      - db-kratos
    image: oryd/kratos:v1.1.0
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
        
  db-kratos:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    volumes:
      - type: volume
        source: db_kratos_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
      - 1025:1025

  app-sample:
    build:
      context: ./app/sample
      target: development
    command: air
    ports:
      - 3000:3000
    environment:
      TERM: xterm-256color
    working_dir: /root/app
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: ./app/sample
        target: /root/app
      - type: volume
        source: api_airtmp
        target: /root/tmp
        volume:
          nocopy: true
      - type: bind
        source: ./.bashrc
        target: /root/.bashrc

volumes:
  db_kratos_data:
  api_airtmp: