version: '3.8'
services:
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.0.0
    ports:
      - 4533:4533 # public
      - 4534:4534 # admin
    command: serve -c /etc/config/kratos/config.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
        
  kratos-migrate:
    depends_on:
      - db-kratos
    image: oryd/kratos:v1.0.0
    command: -c /etc/config/kratos/config.yml migrate sql -e --yes
    volumes:
      - type: bind
        source: ./kratos
        target: /etc/config/kratos
      
  db-kratos:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kratos
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kratos
    volumes:
      - db_kratos_data:/var/lib/postgresql/data

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - 4436:4436
      - 4437:4437
      - 1025:1025

volumes:
  db_kratos_data: