identity:
  schemas:
    - id: customer
      url: base64://ewogICIkc2NoZW1hIjogImh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDcvc2NoZW1hIyIsCiAgInR5cGUiOiAib2JqZWN0IiwKICAicHJvcGVydGllcyI6IHsKICAgICJiYXIiOiB7CiAgICAgICJ0eXBlIjogInN0cmluZyIKICAgIH0KICB9LAogICJyZXF1aXJlZCI6IFsKICAgICJiYXIiCiAgXQp9
    - id: employee
      url: https://foo.bar.com/path/to/employee.traits.schema.json
    - id: employee-v2
      url: file://path/to/employee.v2.traits.schema.json
  default_schema_id: ""
dsn: "postgres://user:
  password@postgresd:5432/database?sslmode=disable&max_conns=20&max_idle_conns=\
  4"
selfservice:
  default_browser_return_url: https://my-app.com/dashboard
  flows:
    logout:
      after:
        default_browser_return_url: https://my-app.com/dashboard
    registration:
      login_hints: false
      ui_url: https://my-app.com/signup
      lifespan: 1h
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
      after:
        password:
          hooks:
            - hook: session
          default_browser_return_url: https://my-app.com/dashboard
        webauthn:
          hooks:
            - hook: session
          default_browser_return_url: https://my-app.com/dashboard
        oidc:
          hooks:
            - hook: session
          default_browser_return_url: https://my-app.com/dashboard
        code:
          hooks:
            - hook: session
          default_browser_return_url: https://my-app.com/dashboard
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
        default_browser_return_url: https://my-app.com/dashboard
      enabled: false
    login:
      lifespan: 1h
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
      after:
        password:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        webauthn:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        oidc:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        code:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        totp:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        lookup_secret:
          hooks:
            - hook: revoke_active_sessions
          default_browser_return_url: https://my-app.com/dashboard
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
        default_browser_return_url: https://my-app.com/dashboard
      ui_url: https://my-app.com/login
    verification:
      ui_url: https://my-app.com/verify
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
        default_browser_return_url: https://my-app.com/dashboard
      lifespan: 1h
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
      use: link
      notify_unknown_recipients: false
      enabled: false
    recovery:
      ui_url: https://my-app.com/verify
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
        default_browser_return_url: https://my-app.com/dashboard
      lifespan: 1h
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
      use: link
      notify_unknown_recipients: false
      enabled: false
    error:
      ui_url: https://my-app.com/kratos-error
    settings:
      lifespan: 1h
      privileged_session_max_age: 1h
      required_aal: aal1
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        totp:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        oidc:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        webauthn:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        lookup_secret:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        profile:
          hooks:
            - hook: web_hook
              config:
                url: http://a.aaa
                method: ""
                can_interrupt: false
                emit_analytics_event: false
                auth:
                  type: api_key
                  config:
                    name: ""
                    value: ""
                    in: header
                body: file:///path/to/body.jsonnet
          default_browser_return_url: https://my-app.com/dashboard
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
        default_browser_return_url: https://my-app.com/dashboard
      before:
        hooks:
          - hook: web_hook
            config:
              url: http://a.aaa
              method: ""
              can_interrupt: false
              emit_analytics_event: false
              auth:
                type: api_key
                config:
                  name: ""
                  value: ""
                  in: header
              body: file:///path/to/body.jsonnet
      ui_url: https://my-app.com/user/settings
  methods:
    link:
      config:
        lifespan: 1h
        base_url: https://my-app.com
      enabled: false
    code:
      mfa_enabled: false
      passwordless_login_fallback_enabled: false
      enabled: false
      config:
        lifespan: 1h
      passwordless_enabled: true
    password:
      config:
        haveibeenpwned_enabled: false
        max_breaches: 0
        ignore_network_errors: false
        min_password_length: 6
        identifier_similarity_check_enabled: false
        haveibeenpwned_host: ""
      enabled: false
    totp:
      config:
        issuer: ""
      enabled: false
    lookup_secret:
      enabled: false
    webauthn:
      config:
        rp:
          id: ory.sh
          display_name: Ory Foundation
          icon: https://www.ory.sh/an-icon.png
        passwordless: false
      enabled: false
    oidc:
      config:
        providers:
          - id: google
            provider: google
            client_id: ""
            mapper_url: file://path/to/oidc.jsonnet
            client_secret: ""
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            scope:
              - offline_access
            microsoft_tenant: common
            subject_source: userinfo
            apple_team_id: KP76DQS54M
            apple_private_key_id: UX56C66723
            apple_private_key: |-
              -----BEGIN PRIVATE KEY-----
              ........
              -----END PRIVATE KEY-----
            requested_claims:
              id_token:
                ? email
                ? email_verified
            organization_id: 12345678-1234-1234-1234-123456789012
            additional_id_token_audiences:
              - 12345678-1234-1234-1234-123456789012
            claims_source: id_token
            label: ""
        base_redirect_uri: https://auth.myexample.org/
      enabled: false
    profile:
      enabled: false
  allowed_return_urls:
    - https://app.my-app.com/dashboard
    - /dashboard
    - https://www.my-app.com/
    - https://*.my-app.com/
courier:
  template_override_path: /conf/courier-templates
  message_retries: 10
  worker:
    pull_wait: 0ns
    pull_count: -100000000
  delivery_strategy: smtp
  http:
    request_config:
      method: ""
      body: file:///path/to/body.jsonnet
      auth:
        type: api_key
        config:
          name: ""
          value: ""
          in: header
      url: https://example.com/api/v1/email
  smtp:
    connection_uri: smtps://foo:bar@my-mailserver:1234/?skip_ssl_verify=false
    client_key_path: ""
    from_address: aaa@a.aa
    from_name: Bob
    headers:
      X-SES-SOURCE-ARN: arn:aws:ses:us-west-2:123456789012:identity/example.com
      X-SES-FROM-ARN: arn:aws:ses:us-west-2:123456789012:identity/example.com
      X-SES-RETURN-PATH-ARN: arn:aws:ses:us-west-2:123456789012:identity/example.com
    local_name: ""
    client_cert_path: ""
  sms:
    from: ""
    request_config:
      url: https://api.twillio.com/sms/send
      method: ""
      body: file:///path/to/body.jsonnet
      auth:
        type: api_key
        config:
          name: ""
          value: ""
          in: header
    enabled: false
  channels:
    - id: sms
      request_config:
        method: ""
        body: file:///path/to/body.jsonnet
        auth:
          type: api_key
          config:
            name: ""
            value: ""
            in: header
        url: https://example.com/api/v1/email
      type: http
  templates:
    recovery_code:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
        sms:
          body:
            plaintext: file://path/to/body.plaintext.gotmpl
      invalid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
    verification:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
        sms:
          body:
            plaintext: file://path/to/body.plaintext.gotmpl
      invalid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
    verification_code:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
        sms:
          body:
            plaintext: file://path/to/body.plaintext.gotmpl
      invalid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
    registration_code:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
    login_code:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
        sms:
          body:
            plaintext: file://path/to/body.plaintext.gotmpl
    recovery:
      valid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
        sms:
          body:
            plaintext: file://path/to/body.plaintext.gotmpl
      invalid:
        email:
          subject: file://path/to/subject.gotmpl
          body:
            html: file://path/to/body.html.gotmpl
            plaintext: file://path/to/body.plaintext.gotmpl
oauth2_provider:
  headers:
    Authorization: Bearer some-token
  override_return_to: false
  url: https://some-slug.projects.oryapis.com
preview:
  default_read_consistency_level: strong
serve:
  public:
    cors:
      allowed_origins:
        - https://example.com
        - https://*.example.com
        - https://*.foo.example.com
      allowed_methods:
        - POST
      allowed_headers:
        - ""
      exposed_headers:
        - ""
      allow_credentials: false
      options_passthrough: false
      max_age: 0
      debug: false
      enabled: false
    base_url: https://my-app.com/
    host: ""
    port: 4433
    socket:
      group: ""
      mode: 0
      owner: ""
    tls:
      cert:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
      key:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
    request_log:
      disable_for_health: false
  admin:
    base_url: https://kratos.private-network:4434/
    host: ""
    port: 4434
    socket:
      group: ""
      mode: 0
      owner: ""
    tls:
      cert:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
      key:
        base64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5NSUlEWlRDQ0FrMmdBd0lCQWdJRVY1eE90REFOQmdr...
        path: path/to/file.pem
    request_log:
      disable_for_health: false
tracing:
  service_name: Ory Hydra
  providers:
    zipkin:
      sampling:
        sampling_ratio: 0.4
      server_url: http://localhost:9411/api/v2/spans
    otlp:
      insecure: false
      sampling:
        sampling_ratio: 0.4
      server_url: localhost:4318
    jaeger:
      sampling:
        trace_id_ratio: 0.5
        server_url: http://localhost:5778/sampling
      local_agent_address: 127.0.0.1:6831
  provider: jaeger
log:
  leak_sensitive_values: false
  redaction_text: ""
  format: json
  level: trace
secrets:
  cookie:
    - ipsumipsumipsumi
  cipher:
    - ipsumipsumipsumipsumipsumipsumip
  default:
    - ipsumipsumipsumi
hashers:
  argon2:
    iterations: 1
    parallelism: 1
    salt_length: 16
    key_length: 16
    expected_duration: 0ns
    expected_deviation: 0ns
    dedicated_memory: 0B
    memory: 0B
  bcrypt:
    cost: 4
  algorithm: argon2
ciphers:
  algorithm: noop
cookies:
  path: ""
  same_site: Strict
  domain: ""
session:
  lifespan: 1h
  cookie:
    name: ""
    persistent: false
    path: ""
    same_site: Strict
    domain: ""
  earliest_possible_extend: 1h
  whoami:
    tokenizer:
      templates:
        a:
          jwks_url: http://a.aaa
          claims_mapper_url: http://a.aaa
          ttl: 0ns
    required_aal: aal1
version: v0.5.0-alpha.1
dev: false
help: false
sqa-opt-out: false
watch-courier: false
expose-metrics-port: 4434
config:
  - ""
clients:
  http:
    private_ip_exception_urls:
      - http://a.aaa
    disallow_private_ip_ranges: false
feature_flags:
  use_continue_with_transitions: false
  cacheable_sessions: false
organizations: []
database:
  cleanup:
    sleep:
      tables: 0ns
    older_than: 0ns
    batch_size: 1