version: v1.2.0

identity:
  default_schema_id: user_v1
  schemas:
    - id: user_v1
      url: file:///etc/config/kratos/identity.schema.user_v1.json

dsn: postgres://kratos:secret@db-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    port: 4433
    base_url: http://localhost:4433
    request_log:
      disable_for_health: true
    cors:
      allowed_origins:
        - http://localhost:3000
        - http://kratos:4433
      allowed_methods:
        - OPTIONS
        - GET
        - POST
      allowed_headers:
        - "*"
      exposed_headers:
        - "*"
      allow_credentials: true
      debug: true
      enabled: true
  admin:
    port: 4434
    base_url: http://localhost:4434
    request_log:
      disable_for_health: true

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000/
    - http://localhost:3000/auth/login
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: true
        min_password_length: 8
        identifier_similarity_check_enabled: true
    profile:
      enabled: true
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: 181885051443-eslsbl8qs7fp4593ureptlq4p1kp48d0.apps.googleusercontent.com
            client_secret: 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
            mapper_url: file:///etc/config/kratos/data-mappers/google.jsonnet
            issuer_url: https://accounts.google.com
            auth_url: https://accounts.google.com/o/oauth2/v2/auth
            token_url: https://www.googleapis.com/oauth2/v4/token
            scope:
              - email
              - profile
              - openid
    # webauthn:
    #   enabled: true
    #   config:
    #     passwordless: true
    #     rp:
    #       display_name: Ory Foundation
    #       id: localhost
    #       icon: https://www.ory.sh/an-icon.png
    # passkey:
    #   enabled: true
    #   config:
    #     rp:
    #       display_name: "My Display Name"
    #       id: localhost
    #       origins:
    #         - http://localhost:4433
    #         - http://localhost:3000
  flows:
    registration:
      enabled: true
      ui_url: http://localhost:3000/auth/registration
      after:
        oidc:
          hooks:
            - hook: session 
          default_browser_return_url: http://localhost:3000/
      enable_legacy_one_step: true
    verification:
      enabled: true
      ui_url: http://localhost:3000/auth/verification
      # form post時は、default_browser_return_urlへはリダイレクトされず、ui_urlへリダイレクトされる
      # https://www.ory.sh/docs/kratos/concepts/browser-redirect-flow-completion#post-verification-redirection
      # after:
      #   default_browser_return_url: http://localhost:3000/auth/login
    recovery:
      enabled: true
      ui_url: http://localhost:3000/auth/recovery
      use: code 
    settings:
      ui_url: http://localhost:3000/my/password
      privileged_session_max_age: 10m
      required_aal: aal1
    login:
      ui_url: http://localhost:3000/auth/login
      after:
        hooks:
          - hook: require_verified_address
        password:
          default_browser_return_url: http://localhost:3000/
        oidc:
          default_browser_return_url: http://localhost:3000/
    logout:
      after:
        default_browser_return_url: http://localhost:3000/

session:
  cookie:
    name: "kratos_session"
secrets:
  cookie:
    - ipsumipsumipsumi
  cipher:
    - ipsumipsumipsumipsumipsumipsumip
  default:
    - ipsumipsumipsumi
courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    from_address: "noreply@local"
    from_name: "kratos"
  templates:
    verification_code:
      valid:
        email:
          body:
            html: file:///etc/config/kratos/templates/verification_code/valid/email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/verification_code/valid/email.body.plaintext.gotmpl
          subject: file:///etc/config/kratos/templates/verification_code/valid/email.subject.gotmpl
    recovery_code:
      valid:
        email:
          body:
            html: file:///etc/config/kratos/templates/recovery_code/valid/email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/recovery_code/valid/email.body.plaintext.gotmpl
          subject: file:///etc/config/kratos/templates/recovery_code/valid/email.subject.gotmpl

log:
  level: debug
  format: text
  leak_sensitive_values: true
