version: v1.0.0

identity:
  default_schema_id: user_v1
  schemas:
    - id: user_v1
      url: file:///etc/config/kratos/identity.schema.user_v1.json

dsn: postgres://kratos:secret@db-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    port: 4533
    base_url: http://localhost:4533
    # cors: リバースプロキシ等を挟まない場合は、セキュリティのためCORS設定が必要
    # tls: リバースプロキシ等でTLSを終端させない場合は、セキュリティのためTLS設定が必要
    request_log:
      disable_for_health: true
  admin:
    port: 4534
    base_url: http://localhost:4534
    # cors: リバースプロキシ等を挟まない場合は、セキュリティのためCORS設定が必要
    # tls: リバースプロキシ等でTLSを終端させない場合は、セキュリティのためTLS設定が必要
    request_log:
      disable_for_health: true

selfservice:
  default_browser_return_url: http://localhost:8000/auth
  allowed_return_urls:
    - http://localhost:8000/auth
    - http://localhost:8000/auth/login
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: true
        min_password_length: 8
        identifier_similarity_check_enabled: true
    profile:
      enabled: true
  flows:
    registration:
      enabled: true
      ui_url: http://localhost:8000/auth/registration
      after:
        password:
          hooks:
            - hook: session
    verification:
      enabled: true
      ui_url: http://localhost:8000/auth/verification
    recovery:
      enabled: true
      ui_url: http://localhost:8000/auth/recovery
      use: code 
    settings:
      ui_url: http://localhost:8000/auth/settings
    login:
      ui_url: http://localhost:8000/auth/login
      after:
        hooks:
          - hook: require_verified_address
    logout:
      after:
        default_browser_return_url: http://localhost:8000/auth/login
    error:
      ui_url: http://localhost:8000/auth/error

session:
  cookie:
    name: "kratos_session"

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    from_address: "noreply@local"
    from_name: "kratos"

log:
  level: trace
  format: json
  leak_sensitive_values: false
