version: v1.0.0

identity:
  default_schema_id: user_v1
  schemas:
    - id: user_v1
      url: file:///etc/config/kratos/identity.schema.user_v1.json

dsn: postgres://kratos:secret@db-kratos-general:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4

serve:
  public:
    port: 4433
    base_url: http://localhost:4433
    request_log:
      disable_for_health: true
  admin:
    port: 4434
    base_url: http://localhost:4434
    request_log:
      disable_for_health: true

selfservice:
  default_browser_return_url: http://localhost:3000/login
  allowed_return_urls:
    - http://localhost:3000/
    - http://localhost:3000/login
    - http://localhost:3000/registration/after
  methods:
    password:
      enabled: true
      config:
        haveibeenpwned_enabled: true
        min_password_length: 8
        identifier_similarity_check_enabled: true
    profile:
      enabled: true
  flows:
    registration:
      enabled: true
      ui_url: http://localhost:3000/registration
      after:
        password:
          default_browser_return_url: http://localhost:3000/registration/after
    verification:
      enabled: true
      ui_url: http://localhost:3000/verification
      # form post時は、default_browser_return_urlへはリダイレクトされず、ui_urlへリダイレクトされる
      # https://www.ory.sh/docs/kratos/concepts/browser-redirect-flow-completion#post-verification-redirection
      # after:
      #   default_browser_return_url: http://localhost:3000/login
    recovery:
      enabled: true
      ui_url: http://localhost:3000/recovery
      use: code 
    settings:
      ui_url: http://localhost:3000/settings/password
      privileged_session_max_age: 10m
      required_aal: aal1
    login:
      ui_url: http://localhost:3000/login
      after:
        hooks:
          - hook: require_verified_address
        password:
          default_browser_return_url: http://localhost:3000/
    logout:
      after:
        default_browser_return_url: http://localhost:3000/
    error:
      ui_url: http://localhost:3000/error

session:
  cookie:
    name: "kratos_general_session"

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
    from_address: "noreply@local"
    from_name: "kratos"
  templates:
    verification_code:
      valid:
        email:
          body:
            html: file:///etc/config/kratos/templates/verification_code/valid/email.body.gotmpl
            plaintext: file:///etc/config/kratos/templates/verification_code/valid/email.body.plaintext.gotmpl
          subject: file:///etc/config/kratos/templates/verification_code/valid/email.subject.gotmpl

log:
  level: debug
  format: text
  leak_sensitive_values: true
